# - name: キー名
#   type: 値のデータ型
#   optional: キーの省略可否 boolean | 'probably-possible' | 'probably-impossible' | 'unknown'
#   description: 説明
#   deprecated: 非推奨の理由
#   details: 詳細説明 （HTML）

- name: buttonTexture
  type: String
  optional: 'probably-impossible'
  description: モデル選択画面で表示されるボタンテクスチャのパス
- name: scale
  type: float
  optional: true
  description: モデルの縮尺
  details: NGTO形式専用
- name: offset
  type: float[]
  optional: true
  description: モデルの描画位置
  details: NGTO形式専用
- name: smoothing
  type: boolean
  optional: probably-possible
  description: スムージングを有効化するか
- name: doCulling
  type: boolean
  optional: probably-possible
  description: 片面表示を行うか
  details: MQO, OBJ形式では使用したほうが負荷が軽減されます。
- name: accuracy
  type: String
  optional: probably-possible
  description: ポリゴンの精度
  details: |
    <ul>
        <li><code>"LOW"</code>: ±16.000の範囲のみ正常に描画</li>
        <li><code>"MEDIUM"</code>: 通常</li>
    </ul>
- name: serverScriptPath
  type: String
  optional: probably-possible
  description: サーバースクリプトのパス
- name: guiScriptPath
  type: String
  optional: probably-possible
  description: GUIスクリプトのパス
- name: guiTexture
  type: String
  optional: probably-possible
  description: GUIテクスチャのパス
- name: renderAABB
  type: float[]
  optional: true
  description: 描画判定範囲の大きさ
- name: customIconTexture
  type: String
  optional: probably-possible
  description: カスタムアイコンのテクスチャ