# KeyName:
#     deprecatedReason: # 非推奨の理由（文字列） null: 不明, undefined: 非推奨ではない
#     description: キーの説明
#     type: String[] # データ型
#     optional: false # 省略の可否 true: 可, false: 不可, "probably": 不明（おそらく可）, その他: 不明（おそらく不可）
#     note: 'テクスチャは16x16ピクセルの画像を推奨' # 追加の説明

buttonTexture:
    description: モデル選択画面で表示されるボタンテクスチャのパス
    type: String
    optional: null

scale:
    description: モデルの縮尺
    type: float
    optional: true
    note: NGTO形式専用
offset:
    description: モデルの描画位置
    type: float[]
    optional: true
    note: NGTO形式専用

smoothing:
    description: スムージング
    type: boolean
    optional: probably

doCulling:
    description: 片面表示
    type: boolean
    optional: probably
    note: MQO, OBJ形式では使用したほうが負荷が軽減されます。

accuracy:
    description: ポリゴンの精度
    type: boolean
    optional: probably
    note: |
        - `"LOW"`: ±16.000の範囲のみ正常に描画
        - `"MEDIUM"`: 通常
        {.grid-list}

serverScriptPath:
    description: サーバースクリプトのパス
    type: String
    optional: probably

guiScriptPath:
    description: GUIスクリプトのパス
    type: String
    optional: probably

guiTexture:
    description: GUIテクスチャのパス
    type: String
    optional: probably

renderAABB:
    description: 描画判定範囲の大きさ
    type: float[]
    optional: true

customIconTexture:
    description: カスタムアイコンのテクスチャ
    type: String
    optional: probably
