# - name: キー名
#   type: 値のデータ型
#   optional: キーの省略可否 boolean | 'probably-possible' | 'probably-impossible' | 'unknown'
#   description: 説明
#   deprecated: 非推奨の理由
#   details: 詳細説明 （HTML）

- name: version
  type: short
  optional: probably-possible
  description: name重複時の優先度決定
  deprecated: false
- name: useCustomColor
  type: boolean
  optional: probably-possible
  description: カスタムカラーの有効化
- name: tags
  type: String
  optional: probably-possible
  description: モデル選択画面での検索キーワード
  details: 複数のキーワードを指定する場合には、1つの半角スペース（<code>U+0020</code>）で区分します。
- name: defaultValues
  type: DMInitValue[]
  optional: true
  description: DataMapのデフォルト値
  details: 詳細不明
- name: defaultData
  type: String
  optional: true
  description: DataMapのデフォルト値
  deprecated: 理由不明