# KeyName:
#     deprecatedReason: # 非推奨の理由（文字列） null: 不明, undefined: 非推奨ではない
#     description: キーの説明
#     type: String[] # データ型
#     optional: false # 省略の可否 true: 可, false: 不可, "probably": 不明（おそらく可）, その他: 不明（おそらく不可）
#     note: 'テクスチャは16x16ピクセルの画像を推奨' # 追加の説明 HTML可

version:
  deprecatedReason: reason
  description: name重複時の優先度決定
  type: short
  optional: probably

userCustomColor:
  description: カスタムカラーの有効化
  type: boolean
  optional: probably

tags:
  description: モデル選択画面での検索キーワード
  type: String
  optional: probably
  note: 複数のキーワードを指定する場合には、1つの半角スペース（<code>U+0020</code>）で区分します。

defaultValues:
  description: DataMapのデフォルト値
  type: DMInitValue[]
  optional: true
  note: 詳細不明

defaultData:
  deprecatedReason: null
  description: DataMapのデフォルト値
  type: String
  optional: true
