# KeyName:
#     deprecatedReason: # 非推奨の理由（文字列） null: 不明, undefined: 非推奨ではない
#     description: キーの説明
#     type: String[] # データ型
#     optional: false # 省略の可否 true: 可, false: 不可, "probably": 不明（おそらく可）, その他: 不明（おそらく不可）
#     note: 'テクスチャは]16x16ピクセルの画像を推奨' # 追加の説明 HTML可

# - name: key-name
#   type: key-type
#   optional: key-omit
#   description: key-description
#   deprecated : key-deprecated

- name: version
  type: short
  optional: probably-possible
  description: name重複時の優先度決定
  deprecated: false
- name: useCustomColor
  type: boolean
  optional: probably-possible
  description: カスタムカラーの有効化
- name: tags
  type: String
  optional: probably-possible
  description: モデル選択画面での検索キーワード
  details: 複数のキーワードを指定する場合には、1つの半角スペース（<code>U+0020</code>）で区分します。
- name: defaultValues
  type: DMInitValue[]
  optional: true
  description: DataMapのデフォルト値
  details: 詳細不明
- name: defaultData
  type: String
  optional: true
  description: DataMapのデフォルト値
  deprecated: 理由不明