# KeyName:
#     deprecatedReason: # 非推奨の理由（文字列） null: 不明, undefined: 非推奨ではない
#     description: キーの説明
#     type: String[] # データ型
#     optional: false # 省略の可否 true: 可, false: 不可, "probably": 不明（おそらく可）, その他: 不明（おそらく不可）
#     note: 'テクスチャは16x16ピクセルの画像を推奨' # 追加の説明

trainName:
    description: 車両名
    type: String
    optional:
    note: 重複不可

trainType:
    description: 車両のタイプ
    type: String
    optional:
    note: |
        - `EC`: 電車
        - `DC`: 気動車
        - `EL`: 電気機関車
        - `DL`: ディーゼル機関車
        - `SL`: 蒸気機関車
        - `CC`: コンテナ車
        - `TC`: タンク車
        - `N`: なし
        {.grid-list}

trainModel2:
    description: 車体モデルのパス
    type: ModelSource
    optional: false

bogieModel3:
    description: 台車モデルのパス（前後別）
    type: ModelSource[]
    optional: false
    note: |
        前後の台車の指定方法
        [front <ModelSource>, back<ModelSource>]

bogieModel2:
    deprecatedReason: 前後別の台車指定方法`bogieModel3`があるため
    description: 台車モデルのパス（前後同じ）
    type: ModelSource
    optional: true

trainModel:
    deprecatedReason: 上位互換の`trainModel2`があるため
    description: 車体モデルのパス
    type: String
    optional: true

bogieModel:
    deprecatedReason: 上位互換の`bogieModel2`があるため
    description: 台車モデルのパス
    type: String
    optional: true

trainTexture:
    deprecatedReason: 上位互換の`trainModel2`があるため
    description: 車体テクスチャのパス
    type: String
    optional: true

bogieTexture:
    deprecatedReason: 上位互換の`bogieModel2`があるため
    description: 台車テクスチャのパス
    type: String
    optional: true

sound_BrakeRelease:
    description: ブレーキ緩解音のパス
    type: String
    optional: probably

sound_BrakeRelease2:
    description: ブレーキ緩解音（弱め）のパス
    type: String
    optional: probably

muteJointSound:
    description: ジョイント音をミュート
    type: boolean
    optional: probably

jointDelay:
    description: 2回めのジョイント音の遅延具合（メートル）
    type: float[][]
    optional: true
    note: 3つ以上の車輪対応、台車前後別。台車のホイールベースを指定すると思う。

isSingleTrain:
    description: 単行かどうか
    type: boolean
    optional: probably

bogiePos:
    description: 台車の位置（x,y,z）
    type: float[][]
    optional: true

trainDistance:
    description: 車体長の半分
    type: float
    optional: true

accelerateion:
    description: 加速度（Block/tick^2^）
    type: float
    optional: true
    note: スペルミスは仕様です

accelerateions:
    description: ノッチ段数とそれぞれのノッチごとの加速度（Block/tick^2^）
    type: float[]
    optional: true
    note: スペルミスは仕様です

maxSpeed:
    description: ノッチごとの速度上限（1~5段）
    type: float[]
    optional: true

deccelerations:
    description: ブレーキノッチ段ごとの減速度（Block/tick^2^）
    type: float[]
    optional: true
    note: |
        スペルミスは仕様です。  
        値は負の値を設定してください。正の値を設定すると加速します。

rolling:
    description: カーブでの傾き具合（0~1）
    type: float
    optional: true

pantoPos:
    description: パンタグラフの摺板位置（x, z, minY, maxY）
    type: float[][]
    optional: probably

rollSpeedCoefficient:
    description: 車体が揺れる速度
    type: float
    optional: probably
    note: |
        車体の揺れ方は、基本波と変調波の合成波によって定義されている
        2つの波が進行する速度は、それぞれ車両の速度に比例するが、その際の比例定数

        ...たぶん

rollVariationCoefficient:
    description: 車体の揺れ方
    type: float
    optional: probably
    note: |
        大きい値を指定すると変調波の周波数が高くなり、揺れが細かくなる
        小さい値を指定すると変調波の周波数が低くなり、揺れが緩やかになる

        ...と思う

rollWidthCoefficient:
    description: 車体が揺れる量
    type: float
    optional: probably
    note: |
        車体が最終的に揺れる量は合成波に比例するが、その際の比例定数
        わかりやすく左右に揺れる大きさを変えることができる

        ...はず

userVariableAcceleration:
    description: サーバースクリプトでの加速度制御の有効化
    type: boolean
    optional: true

useVariableDeceleration:
    description: サーバースクリプトでの減速度制御の有効化
    type: boolean
    optional: true

sound_CpFin:
    description: コンプレッサー終了音のパス
    type: String
    optional: probably

sound_Joint:
    description: ジョイント音のパス
    type: String
    optional: probably

sound_JointReverb:
    description: 反響ありのジョイント音のパス
    type: String
    optional: probably
