# - name: キー名
#   type: 値のデータ型
#   optional: キーの省略可否 boolean | 'probably-possible' | 'probably-impossible' | 'unknown'
#   description: 説明
#   deprecated: 非推奨の理由
#   details: 詳細説明 （HTML）

- name: size
  type: float[]
  optional: true
  description: 当たり判定サイズ
  details: <code>[width, height]</code>

- name: rollsignTexture
  type: String
  optional: probably-possible
  description: 方向幕テクスチャのパス

- name: rollsignNames
  type: String[]
  optional: probably-possible
  description: 方向幕の名前

- name: rollsigns
  type: Rollsign[]
  optional: probably-possible
  description: 方向幕

- name: customButtons
  type: String[][]
  optional: true
  description: カスタムボタン
  details: <code>[ボタン, ボタンの状態名]</code>

- name: customButtonTips
  type: String[]
  optional: true
  description: 各ボタンの説明

- name: door_left
  type: VehicleParts[]
  optional: probably-possible
  description: 左側ドアの動作

- name: door_right
  type: VehicleParts[]
  optional: probably-possible
  description: 右側ドアの動作

- name: pantograph_front
  type: VehicleParts[]
  optional: probably-possible
  description: 前方パンタグラフの動作

- name: pantograph_back
  type: VehicleParts[]
  optional: probably-possible
  description: 後方パンタグラフの動作

- name: sound_Stop
  type: String
  optional: probably-possible
  description: 停車時の音声のパス

- name: sound_S_A
  type: String
  optional: probably-possible
  description: 停車~加速時の音声のパス

- name: sound_Acceleration
  type: String
  optional: probably-possible
  description: 加速時の音声のパス

- name: sound_Deceleration
  type: String
  optional: probably-possible
  description: 減速時の音声のパス

- name: sound_D_S
  type: String
  optional: probably-possible
  description: 減速~停車時の音声のパス

- name: sound_Horn
  type: String
  optional: probably-possible
  description: 警笛の音声のパス

- name: sound_DoorOpen
  type: String
  optional: probably-possible
  description: ドア開扉時の音声のパス

- name: sound_DoorClose
  type: String
  optional: probably-possible
  description: ドア閉扉時の音声のパス

- name: sound_ATSChime
  type: String
  optional: probably-possible
  description:

- name: sound_ATSBell
  type: String
  optional: probably-possible
  description:

- name: sound_Announcement
  type: String[][]
  optional: probably-possible
  description: 車内放送の音声のパス
  details: <code>[表示名, 音声]</code>

- name: soundScriptPath
  type: String
  optional: probably-possible
  description: 音声スクリプトのパス

- name: smoke
  type: Object[][]
  optional: probably-possible
  description: 煙
  details: <code>[float x, float y, float z, String name, int min, int max, float speed]</code>

- name: headLights
  type: Light[]
  optional: probably-possible
  description: 前照灯

- name: tailLights
  type: Light[]
  optional: probably-possible
  description: 尾灯

- name: interiorLights
  type: Light[]
  optional: probably-possible
  description: 車内灯

- name: slotPos
  type: float[][]
  optional: true
  description: 座席
  details: |
    <pre><code>[x, y, z, type]</code></pre>
    単位はメートル<br>
    <strong>typeの値</strong>  
    <ul>
    <li><code>0</code>: なし（当たり判定のみ）</li>
    <li><code>1</code>: クロスシート</li>
    <li><code>2</code>: 表示なし（3Dモデルで座席を制作してある場合など）</li>
    <li><code>3</code>: 寝台（未実装）</li>
    </ul>

- name: seatPos
  type: int[][]
  optional: probably-possible
  description: 座席
  deprecated: 上位互換の <code>slotPos</code> があるため
  details: 単位はブロック

- name: seatPosF
  type: unknown
  optional: probably-possible
  description: 座席（RTM2用）
  details: |
    1.12.2に対応するには <code>slotPos</code> に加え、こちらも使う  
    値は <code>slotPos</code> と同じでよい

- name: playerPos
  type: float[][]
  optional: true
  description: プレイヤーの位置
  details: <pre><code>[x, y, z]</code></pre>

- name: notDisplayCab
  type: boolean
  optional: probably-possible
  description: 運転台非表示

- name: wheelRotationSpeed
  type: float
  optional: true
  description: 車輪の回転速度