name: Notify IndexNow

on:
    workflow_run:
        workflows: ['Update Sitemap'] # 既存のsitemap生成後にトリガー
        types:
            - completed

jobs:
    notify-indexnow:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Extract URLs from sitemap.xml and notify IndexNow
              run: |
                  API_KEY="9c871a252ea34ff48cdbb80f9f9b095e"
                  SITE_HOST="https://rtmwiki.kotl.io"
                  KEY_LOCATION="https://rtmwiki.kotl.io/9c871a252ea34ff48cdbb80f9f9b095e.txt"  # APIキーのURL

                  # sitemap.xml から URL を抽出
                  grep -oP '(?<=<loc>).*?(?=</loc>)' sitemap.xml > urls.txt

                  echo "Notifying IndexNow..."

                  # URLリストを作成
                  URL_LIST=()
                  while read -r url; do
                  URL_LIST+=("\"$url\"")
                  done < urls.txt

                  # URLリストをカンマ区切りで結合
                  URL_LIST_JSON=$(IFS=,; echo "[${URL_LIST[*]}]")

                  # IndexNowに通知
                  response=$(curl -s -X POST "https://api.indexnow.org/IndexNow" \
                  -H "Content-Type: application/json; charset=utf-8" \
                  -d "{
                      \"host\": \"$SITE_HOST\",
                      \"key\": \"$API_KEY\",
                      \"keyLocation\": \"$KEY_LOCATION\",
                      \"urlList\": $URL_LIST_JSON
                  }")

                  echo "Response: $response"
