name: Notify Discord on File Push

on:
  push:
    branches:
      - main  # 監視するブランチを指定
    paths: '**.md'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # リポジトリ全体を取得するために0を指定

    #   - name: Get changed files
    #     id: changed_files
    #     run: |
    #         echo ${{ github.event.before }}
    #         echo ${{ github.sha }}
    #         git diff --name-only ${{ github.event.before }} ${{ github.sha }}
    
      - name: Run script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
          BEFORE_SHA: ${{ github.event.before }}
          AFTER_SHA: ${{ github.sha }}
        run: node .github\workflows\notify_discord.js