# とりあえずChatGPTに書かせた
# 問題なさそうなのでcommitしとく
# よくわからないが、このワークフローが行った変更にこれ自身が反応することはないのだろうか

name: Update Sitemap  # ワークフローの名前（GitHub Actions の UI で表示される）

on:
  push: # `main`ブランチにMarkdownファイルがpushされた時に実行する
    branches:
      - main
    paths:
      - '**.md'
  workflow_dispatch:  # 手動実行も可能にする

jobs:
  update-sitemap:
    runs-on: ubuntu-latest  # GitHub Actions の実行環境として Ubuntu を使用する

    steps:        
      - name: Checkout repository
        uses: actions/checkout@v4  # リポジトリの最新コードを取得

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'  # 最新のNode.jsを使用

      - name: Check Node.js version
        run: node --version

      - name: Generate sitemap
        run: node .github/workflows/sitemap-generator.js  # `sitemap-generator.js` を実行して `sitemap.xml` を生成

      - name: Commit and push sitemap
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add sitemap.xml
          git diff --staged --quiet || (git commit -m "Auto-update sitemap" && git push)
